### ISSUE TITLE
Issue in Scanning Kanji QR code using camera in xamarin in Release Mode

### ISSUE THREAD

**Issue by vinukodi** [Bacon/BaconQrCode#81] opened 2021-02-09 14:06 UTC
I have implemented an Xamarin App which uses the zxing library for scan the QR. When app is **deployed** to **android device** in **debug mode** it scan the QR but not in **RELEASE MODE**. Can you suggest me the best way to fix this issue.?

ZXing.Net.Mobile nuget version 2.4.1

Here I have added code snippet which I have used. Also the QR code.

![image](https://user-images.githubusercontent.com/78755115/107373901-08201800-6b0d-11eb-995c-02ea1d7f3ba0.png)

![image](https://user-images.githubusercontent.com/78755115/107374243-63eaa100-6b0d-11eb-8ba3-ba6f22213add.png)

**Comment by DASPRiD** [comment] 2022-01-31 00:12
Closing as linked issue suggests that the the QR code scans as intended.

**Closed by DASPRiD** 2022-01-31 00:12 UTC
