### ISSUE TITLE
BaconQrCode\Exception\RuntimeException: You need to install the imagick extension to use this back end

### ISSUE THREAD

**Issue by aFluxx** [Bacon/BaconQrCode#61] opened 2019-04-05 16:49 UTC
Hello there,

I'm having an issue when trying to run phpunit together with this package:

```
1) Tests\Feature\PigeonIndexTest::a_user_can_only_see_their_own_pigeons
BaconQrCode\Exception\RuntimeException: You need to install the imagick extension to use this back end

C:\Users\aFluxx\Desktop\pigeome\vendor\bacon\bacon-qr-code\src\Renderer\Image\ImagickImageBackEnd.php:64
C:\Users\aFluxx\Desktop\pigeome\vendor\pragmarx\google2fa-qrcode\src\Google2FA.php:40
C:\Users\aFluxx\Desktop\pigeome\vendor\pragmarx\google2fa-laravel\src\Google2FA.php:31
C:\Users\aFluxx\Desktop\pigeome\vendor\pragmarx\google2fa-laravel\src\Support\Authenticator.php:37
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Container\Container.php:812
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Container\Container.php:658
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Container\Container.php:609
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:759
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:121
C:\Users\aFluxx\Desktop\pigeome\vendor\pragmarx\google2fa-laravel\src\Middleware.php:12
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php:43
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes.php:30
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath.php:33
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect.php:56
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\mcamara\laravel-localization\src\Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter.php:45
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\app\Http\Middleware\MarkNotificationAsRead.php:24
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:75
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php:58
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:66
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Router.php:694
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Router.php:668
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Router.php:633
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Router.php:622
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
C:\Users\aFluxx\Desktop\pigeome\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php:58
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\fideloper\proxy\src\TrustProxies.php:57
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:62
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Testing\Concerns\MakesHttpRequests.php:345
C:\Users\aFluxx\Desktop\pigeome\vendor\laravel\framework\src\Illuminate\Foundation\Testing\Concerns\MakesHttpRequests.php:168
C:\Users\aFluxx\Desktop\pigeome\tests\Feature\PigeonIndexTest.php:51

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
Script .\vendor\bin\phpunit handling the test event returned with error code 2
```

I'm trying to run sq_lite in ;memory: any idea how I can fix this?

**Comment by aFluxx** [comment] 2019-04-05 16:55
Ok, so aparantly this happend after I installed to the latest version of this package 2.0, when I downgraded to "bacon/bacon-qr-code": "1.0.3", everything started working again.

**Comment by DASPRiD** [comment] 2019-04-05 18:13
Duplicate of #60

**Closed by DASPRiD** 2019-04-05 18:13 UTC
Labels: bug, duplicate
